---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatgpt-mirai-qq-bot
  labels:
    app: chatgpt-mirai-qq-bot
    tier: server
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: chatgpt-mirai-qq-bot
      tier: server
  template:
    metadata:
      labels:
        app: chatgpt-mirai-qq-bot
        tier: server
    spec:
      {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
      {{- end }}
      containers:
        - name: chatgpt-mirai-qq-bot
          image: "lss233/chatgpt-mirai-qq-bot:{{ .Values.imageTag }}"
          imagePullPolicy: Always
          ports:
          - containerPort: 14500
          env:
          - name: SERVICE_ENV
            value: "prod"
          - name: K8S_NAMESPACE
            value: {{ .Release.Namespace }}

          volumeMounts:
            - name: app-log
              mountPath: /tmp
            - name: config
              mountPath: /app/config.cfg
              subPath: config.cfg

      volumes:
        - name: app-log
          emptyDir: {}
        - name: config
          configMap:
            name: app-config

---
apiVersion: v1
kind: Service
metadata:
  name: chatgpt-mirai-qq-bot-svc
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 14500
      targetPort: 14500
  selector:
    app: chatgpt-mirai-qq-bot
    tier: server

